### ISSUE TITLE
code detail in SENN_audio_eval.py

### ISSUE THREAD

**Issue by maogewudi007** [zhr1201/CNN-for-single-channel-speech-enhancement#11]
Hi, @zhr1201 .  
1 What is the meaning of "0.5016" in “line 151: out_audio[i * NMOVE: i * NMOVE + NFFT] += frame_out_tmp * 0.5016 ”  ?
2 How to count "validation_samples" in SENN_train.py?
Best wishes!

**Comment by zhr1201** [comment]
1.  It is meant to make sure if the audio is unprocessed, the amplitude will be the same for the output and input.
2.  Not sure what you mean. Wouldn't it work if you just print out the dimension?

**Comment by jeongHwarr** [comment]
What is the meaning of the mul_fac variable set to a value of 0.2?

**Comment by jeongHwarr** [comment]
and how did you get 0.5016? what formula did you use to calculate? thank you

**Comment by maogewudi007** [comment]
> and how did you get 0.5016? what formula did you use to calculate? thank you
see you again

**Comment by maogewudi007** [comment]
> and how did you get 0.5016? what formula did you use to calculate? thank you
Emmm....., see you again. Are you interested in speech enhancement?  We can discuss  it，my email is yahui2727@163.com. Looking forward to your replay！

**Comment by zhr1201** [comment]
This is like a recovering factor that makes the amplitude the same as the input despite all those transformations and window multiplications.
